# Generated by Django 4.2.2 on 2023-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userdetails_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
